/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mapping.mapping;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mapping.mapping.Definition#getFormalElement <em>Formal Element</em>}</li>
 *   <li>{@link org.xtext.example.mapping.mapping.Definition#getUmlElement <em>Uml Element</em>}</li>
 *   <li>{@link org.xtext.example.mapping.mapping.Definition#getTypeElement <em>Type Element</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mapping.mapping.MappingPackage#getDefinition()
 * @model
 * @generated
 */
public interface Definition extends EObject
{
  /**
   * Returns the value of the '<em><b>Formal Element</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Formal Element</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Formal Element</em>' containment reference.
   * @see #setFormalElement(FormalElement)
   * @see org.xtext.example.mapping.mapping.MappingPackage#getDefinition_FormalElement()
   * @model containment="true"
   * @generated
   */
  FormalElement getFormalElement();

  /**
   * Sets the value of the '{@link org.xtext.example.mapping.mapping.Definition#getFormalElement <em>Formal Element</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Formal Element</em>' containment reference.
   * @see #getFormalElement()
   * @generated
   */
  void setFormalElement(FormalElement value);

  /**
   * Returns the value of the '<em><b>Uml Element</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Uml Element</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Uml Element</em>' containment reference.
   * @see #setUmlElement(UmlElement)
   * @see org.xtext.example.mapping.mapping.MappingPackage#getDefinition_UmlElement()
   * @model containment="true"
   * @generated
   */
  UmlElement getUmlElement();

  /**
   * Sets the value of the '{@link org.xtext.example.mapping.mapping.Definition#getUmlElement <em>Uml Element</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Uml Element</em>' containment reference.
   * @see #getUmlElement()
   * @generated
   */
  void setUmlElement(UmlElement value);

  /**
   * Returns the value of the '<em><b>Type Element</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type Element</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type Element</em>' containment reference.
   * @see #setTypeElement(TypeElement)
   * @see org.xtext.example.mapping.mapping.MappingPackage#getDefinition_TypeElement()
   * @model containment="true"
   * @generated
   */
  TypeElement getTypeElement();

  /**
   * Sets the value of the '{@link org.xtext.example.mapping.mapping.Definition#getTypeElement <em>Type Element</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type Element</em>' containment reference.
   * @see #getTypeElement()
   * @generated
   */
  void setTypeElement(TypeElement value);

} // Definition
