/*
 * generated by Xtext 2.9.1
 */
package org.xtext.example.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTraceScopeProvider extends DelegatingScopeProvider {
}
