/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mapping;

import org.xtext.example.mapping.AbstractMappingRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class MappingRuntimeModule extends AbstractMappingRuntimeModule {
}
