/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.dsl.scoping;

import org.xtext.example.dsl.scoping.AbstractTraceScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class TraceScopeProvider extends AbstractTraceScopeProvider {
}
