/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.dsl.trace.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.dsl.trace.Element;
import org.xtext.example.dsl.trace.FormalElement;
import org.xtext.example.dsl.trace.TracePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Formal Element</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.dsl.trace.impl.FormalElementImpl#getFormalElement <em>Formal Element</em>}</li>
 *   <li>{@link org.xtext.example.dsl.trace.impl.FormalElementImpl#getElement <em>Element</em>}</li>
 * </ul>
 *
 * @generated
 */
public class FormalElementImpl extends MinimalEObjectImpl.Container implements FormalElement
{
  /**
   * The cached value of the '{@link #getFormalElement() <em>Formal Element</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFormalElement()
   * @generated
   * @ordered
   */
  protected org.xtext.example.mapping.mapping.FormalElement formalElement;

  /**
   * The cached value of the '{@link #getElement() <em>Element</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getElement()
   * @generated
   * @ordered
   */
  protected Element element;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FormalElementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TracePackage.Literals.FORMAL_ELEMENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public org.xtext.example.mapping.mapping.FormalElement getFormalElement()
  {
    if (formalElement != null && formalElement.eIsProxy())
    {
      InternalEObject oldFormalElement = (InternalEObject)formalElement;
      formalElement = (org.xtext.example.mapping.mapping.FormalElement)eResolveProxy(oldFormalElement);
      if (formalElement != oldFormalElement)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, TracePackage.FORMAL_ELEMENT__FORMAL_ELEMENT, oldFormalElement, formalElement));
      }
    }
    return formalElement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public org.xtext.example.mapping.mapping.FormalElement basicGetFormalElement()
  {
    return formalElement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setFormalElement(org.xtext.example.mapping.mapping.FormalElement newFormalElement)
  {
    org.xtext.example.mapping.mapping.FormalElement oldFormalElement = formalElement;
    formalElement = newFormalElement;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TracePackage.FORMAL_ELEMENT__FORMAL_ELEMENT, oldFormalElement, formalElement));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Element getElement()
  {
    return element;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetElement(Element newElement, NotificationChain msgs)
  {
    Element oldElement = element;
    element = newElement;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, TracePackage.FORMAL_ELEMENT__ELEMENT, oldElement, newElement);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setElement(Element newElement)
  {
    if (newElement != element)
    {
      NotificationChain msgs = null;
      if (element != null)
        msgs = ((InternalEObject)element).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - TracePackage.FORMAL_ELEMENT__ELEMENT, null, msgs);
      if (newElement != null)
        msgs = ((InternalEObject)newElement).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - TracePackage.FORMAL_ELEMENT__ELEMENT, null, msgs);
      msgs = basicSetElement(newElement, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TracePackage.FORMAL_ELEMENT__ELEMENT, newElement, newElement));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case TracePackage.FORMAL_ELEMENT__ELEMENT:
        return basicSetElement(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TracePackage.FORMAL_ELEMENT__FORMAL_ELEMENT:
        if (resolve) return getFormalElement();
        return basicGetFormalElement();
      case TracePackage.FORMAL_ELEMENT__ELEMENT:
        return getElement();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TracePackage.FORMAL_ELEMENT__FORMAL_ELEMENT:
        setFormalElement((org.xtext.example.mapping.mapping.FormalElement)newValue);
        return;
      case TracePackage.FORMAL_ELEMENT__ELEMENT:
        setElement((Element)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TracePackage.FORMAL_ELEMENT__FORMAL_ELEMENT:
        setFormalElement((org.xtext.example.mapping.mapping.FormalElement)null);
        return;
      case TracePackage.FORMAL_ELEMENT__ELEMENT:
        setElement((Element)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TracePackage.FORMAL_ELEMENT__FORMAL_ELEMENT:
        return formalElement != null;
      case TracePackage.FORMAL_ELEMENT__ELEMENT:
        return element != null;
    }
    return super.eIsSet(featureID);
  }

} //FormalElementImpl
