/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.example.dsl.ui.AbstractTraceUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class TraceUiModule extends AbstractTraceUiModule {
  public TraceUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
