/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.dsl;

import org.xtext.example.dsl.TraceStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class TraceStandaloneSetup extends TraceStandaloneSetupGenerated {
  public static void doSetup() {
    TraceStandaloneSetup _traceStandaloneSetup = new TraceStandaloneSetup();
    _traceStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
