/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.dsl;

import org.xtext.example.dsl.AbstractTraceRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class TraceRuntimeModule extends AbstractTraceRuntimeModule {
}
