/*
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mapping.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.mapping.ui.internal.MappingActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MappingExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return MappingActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return MappingActivator.getInstance().getInjector(MappingActivator.ORG_XTEXT_EXAMPLE_MAPPING_MAPPING);
	}
	
}
