/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.dsl.validation;

import org.xtext.example.dsl.validation.AbstractTraceValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class TraceValidator extends AbstractTraceValidator {
}
