/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.dsl.trace;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Diagram</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.dsl.trace.Diagram#getKind <em>Kind</em>}</li>
 *   <li>{@link org.xtext.example.dsl.trace.Diagram#getModel <em>Model</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.dsl.trace.TracePackage#getDiagram()
 * @model
 * @generated
 */
public interface Diagram extends EObject
{
  /**
   * Returns the value of the '<em><b>Kind</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.dsl.trace.DiagramKind}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Kind</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Kind</em>' attribute.
   * @see org.xtext.example.dsl.trace.DiagramKind
   * @see #setKind(DiagramKind)
   * @see org.xtext.example.dsl.trace.TracePackage#getDiagram_Kind()
   * @model
   * @generated
   */
  DiagramKind getKind();

  /**
   * Sets the value of the '{@link org.xtext.example.dsl.trace.Diagram#getKind <em>Kind</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Kind</em>' attribute.
   * @see org.xtext.example.dsl.trace.DiagramKind
   * @see #getKind()
   * @generated
   */
  void setKind(DiagramKind value);

  /**
   * Returns the value of the '<em><b>Model</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Model</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Model</em>' containment reference.
   * @see #setModel(Model)
   * @see org.xtext.example.dsl.trace.TracePackage#getDiagram_Model()
   * @model containment="true"
   * @generated
   */
  Model getModel();

  /**
   * Sets the value of the '{@link org.xtext.example.dsl.trace.Diagram#getModel <em>Model</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Model</em>' containment reference.
   * @see #getModel()
   * @generated
   */
  void setModel(Model value);

} // Diagram
