/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.dsl.trace;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Diagram Kind</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.xtext.example.dsl.trace.TracePackage#getDiagramKind()
 * @model
 * @generated
 */
public enum DiagramKind implements Enumerator
{
  /**
   * The '<em><b>CLASSDIAGRAM</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CLASSDIAGRAM_VALUE
   * @generated
   * @ordered
   */
  CLASSDIAGRAM(0, "CLASSDIAGRAM", "ClassDiagram"),

  /**
   * The '<em><b>SEQUENCEDIAGRAM</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SEQUENCEDIAGRAM_VALUE
   * @generated
   * @ordered
   */
  SEQUENCEDIAGRAM(1, "SEQUENCEDIAGRAM", "SequenceDiagram"),

  /**
   * The '<em><b>STATEDIAGRAM</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #STATEDIAGRAM_VALUE
   * @generated
   * @ordered
   */
  STATEDIAGRAM(2, "STATEDIAGRAM", "StateDiagram"),

  /**
   * The '<em><b>OBJECTDIAGRAM</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #OBJECTDIAGRAM_VALUE
   * @generated
   * @ordered
   */
  OBJECTDIAGRAM(3, "OBJECTDIAGRAM", "ObjectDiagram"),

  /**
   * The '<em><b>INTERACTIONOVERVIEWDIAGRAM</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #INTERACTIONOVERVIEWDIAGRAM_VALUE
   * @generated
   * @ordered
   */
  INTERACTIONOVERVIEWDIAGRAM(4, "INTERACTIONOVERVIEWDIAGRAM", "InteractionOverviewDiagram");

  /**
   * The '<em><b>CLASSDIAGRAM</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>CLASSDIAGRAM</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #CLASSDIAGRAM
   * @model literal="ClassDiagram"
   * @generated
   * @ordered
   */
  public static final int CLASSDIAGRAM_VALUE = 0;

  /**
   * The '<em><b>SEQUENCEDIAGRAM</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>SEQUENCEDIAGRAM</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #SEQUENCEDIAGRAM
   * @model literal="SequenceDiagram"
   * @generated
   * @ordered
   */
  public static final int SEQUENCEDIAGRAM_VALUE = 1;

  /**
   * The '<em><b>STATEDIAGRAM</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>STATEDIAGRAM</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #STATEDIAGRAM
   * @model literal="StateDiagram"
   * @generated
   * @ordered
   */
  public static final int STATEDIAGRAM_VALUE = 2;

  /**
   * The '<em><b>OBJECTDIAGRAM</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>OBJECTDIAGRAM</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #OBJECTDIAGRAM
   * @model literal="ObjectDiagram"
   * @generated
   * @ordered
   */
  public static final int OBJECTDIAGRAM_VALUE = 3;

  /**
   * The '<em><b>INTERACTIONOVERVIEWDIAGRAM</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>INTERACTIONOVERVIEWDIAGRAM</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #INTERACTIONOVERVIEWDIAGRAM
   * @model literal="InteractionOverviewDiagram"
   * @generated
   * @ordered
   */
  public static final int INTERACTIONOVERVIEWDIAGRAM_VALUE = 4;

  /**
   * An array of all the '<em><b>Diagram Kind</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final DiagramKind[] VALUES_ARRAY =
    new DiagramKind[]
    {
      CLASSDIAGRAM,
      SEQUENCEDIAGRAM,
      STATEDIAGRAM,
      OBJECTDIAGRAM,
      INTERACTIONOVERVIEWDIAGRAM,
    };

  /**
   * A public read-only list of all the '<em><b>Diagram Kind</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<DiagramKind> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Diagram Kind</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static DiagramKind get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      DiagramKind result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Diagram Kind</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static DiagramKind getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      DiagramKind result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Diagram Kind</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static DiagramKind get(int value)
  {
    switch (value)
    {
      case CLASSDIAGRAM_VALUE: return CLASSDIAGRAM;
      case SEQUENCEDIAGRAM_VALUE: return SEQUENCEDIAGRAM;
      case STATEDIAGRAM_VALUE: return STATEDIAGRAM;
      case OBJECTDIAGRAM_VALUE: return OBJECTDIAGRAM;
      case INTERACTIONOVERVIEWDIAGRAM_VALUE: return INTERACTIONOVERVIEWDIAGRAM;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private DiagramKind(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //DiagramKind
