/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.dsl.trace;

import org.eclipse.emf.ecore.EObject;

import org.xtext.example.mapping.mapping.TypeElement;
import org.xtext.example.mapping.mapping.UmlElement;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.dsl.trace.Element#getTypeElement <em>Type Element</em>}</li>
 *   <li>{@link org.xtext.example.dsl.trace.Element#getUmlElement <em>Uml Element</em>}</li>
 *   <li>{@link org.xtext.example.dsl.trace.Element#getDiagram <em>Diagram</em>}</li>
 *   <li>{@link org.xtext.example.dsl.trace.Element#getModel <em>Model</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.dsl.trace.TracePackage#getElement()
 * @model
 * @generated
 */
public interface Element extends EObject
{
  /**
   * Returns the value of the '<em><b>Type Element</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type Element</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type Element</em>' reference.
   * @see #setTypeElement(TypeElement)
   * @see org.xtext.example.dsl.trace.TracePackage#getElement_TypeElement()
   * @model
   * @generated
   */
  TypeElement getTypeElement();

  /**
   * Sets the value of the '{@link org.xtext.example.dsl.trace.Element#getTypeElement <em>Type Element</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type Element</em>' reference.
   * @see #getTypeElement()
   * @generated
   */
  void setTypeElement(TypeElement value);

  /**
   * Returns the value of the '<em><b>Uml Element</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Uml Element</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Uml Element</em>' reference.
   * @see #setUmlElement(UmlElement)
   * @see org.xtext.example.dsl.trace.TracePackage#getElement_UmlElement()
   * @model
   * @generated
   */
  UmlElement getUmlElement();

  /**
   * Sets the value of the '{@link org.xtext.example.dsl.trace.Element#getUmlElement <em>Uml Element</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Uml Element</em>' reference.
   * @see #getUmlElement()
   * @generated
   */
  void setUmlElement(UmlElement value);

  /**
   * Returns the value of the '<em><b>Diagram</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Diagram</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Diagram</em>' containment reference.
   * @see #setDiagram(Diagram)
   * @see org.xtext.example.dsl.trace.TracePackage#getElement_Diagram()
   * @model containment="true"
   * @generated
   */
  Diagram getDiagram();

  /**
   * Sets the value of the '{@link org.xtext.example.dsl.trace.Element#getDiagram <em>Diagram</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Diagram</em>' containment reference.
   * @see #getDiagram()
   * @generated
   */
  void setDiagram(Diagram value);

  /**
   * Returns the value of the '<em><b>Model</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Model</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Model</em>' containment reference.
   * @see #setModel(Model)
   * @see org.xtext.example.dsl.trace.TracePackage#getElement_Model()
   * @model containment="true"
   * @generated
   */
  Model getModel();

  /**
   * Sets the value of the '{@link org.xtext.example.dsl.trace.Element#getModel <em>Model</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Model</em>' containment reference.
   * @see #getModel()
   * @generated
   */
  void setModel(Model value);

} // Element
