/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.dsl.trace;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Formal Result</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.dsl.trace.FormalResult#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.dsl.trace.FormalResult#getTimenodes <em>Timenodes</em>}</li>
 *   <li>{@link org.xtext.example.dsl.trace.FormalResult#getFormalElements <em>Formal Elements</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.dsl.trace.TracePackage#getFormalResult()
 * @model
 * @generated
 */
public interface FormalResult extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.dsl.trace.TracePackage#getFormalResult_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.dsl.trace.FormalResult#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Timenodes</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.dsl.trace.TimeNode}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Timenodes</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Timenodes</em>' containment reference list.
   * @see org.xtext.example.dsl.trace.TracePackage#getFormalResult_Timenodes()
   * @model containment="true"
   * @generated
   */
  EList<TimeNode> getTimenodes();

  /**
   * Returns the value of the '<em><b>Formal Elements</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.dsl.trace.FormalElement}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Formal Elements</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Formal Elements</em>' containment reference list.
   * @see org.xtext.example.dsl.trace.TracePackage#getFormalResult_FormalElements()
   * @model containment="true"
   * @generated
   */
  EList<FormalElement> getFormalElements();

} // FormalResult
