/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.dsl.trace;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Formal Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.dsl.trace.FormalElement#getFormalElement <em>Formal Element</em>}</li>
 *   <li>{@link org.xtext.example.dsl.trace.FormalElement#getElement <em>Element</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.dsl.trace.TracePackage#getFormalElement()
 * @model
 * @generated
 */
public interface FormalElement extends EObject
{
  /**
   * Returns the value of the '<em><b>Formal Element</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Formal Element</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Formal Element</em>' reference.
   * @see #setFormalElement(org.xtext.example.mapping.mapping.FormalElement)
   * @see org.xtext.example.dsl.trace.TracePackage#getFormalElement_FormalElement()
   * @model
   * @generated
   */
  org.xtext.example.mapping.mapping.FormalElement getFormalElement();

  /**
   * Sets the value of the '{@link org.xtext.example.dsl.trace.FormalElement#getFormalElement <em>Formal Element</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Formal Element</em>' reference.
   * @see #getFormalElement()
   * @generated
   */
  void setFormalElement(org.xtext.example.mapping.mapping.FormalElement value);

  /**
   * Returns the value of the '<em><b>Element</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Element</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Element</em>' containment reference.
   * @see #setElement(Element)
   * @see org.xtext.example.dsl.trace.TracePackage#getFormalElement_Element()
   * @model containment="true"
   * @generated
   */
  Element getElement();

  /**
   * Sets the value of the '{@link org.xtext.example.dsl.trace.FormalElement#getElement <em>Element</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Element</em>' containment reference.
   * @see #getElement()
   * @generated
   */
  void setElement(Element value);

} // FormalElement
