/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.dsl.trace;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.dsl.trace.Model#getKind <em>Kind</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.dsl.trace.TracePackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Kind</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.dsl.trace.ModelKind}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Kind</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Kind</em>' attribute.
   * @see org.xtext.example.dsl.trace.ModelKind
   * @see #setKind(ModelKind)
   * @see org.xtext.example.dsl.trace.TracePackage#getModel_Kind()
   * @model
   * @generated
   */
  ModelKind getKind();

  /**
   * Sets the value of the '{@link org.xtext.example.dsl.trace.Model#getKind <em>Kind</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Kind</em>' attribute.
   * @see org.xtext.example.dsl.trace.ModelKind
   * @see #getKind()
   * @generated
   */
  void setKind(ModelKind value);

} // Model
