/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.dsl.trace;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.dsl.trace.TraceFactory
 * @model kind="package"
 * @generated
 */
public interface TracePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "trace";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/dsl/Trace";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "trace";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  TracePackage eINSTANCE = org.xtext.example.dsl.trace.impl.TracePackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.dsl.trace.impl.FormalResultImpl <em>Formal Result</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.dsl.trace.impl.FormalResultImpl
   * @see org.xtext.example.dsl.trace.impl.TracePackageImpl#getFormalResult()
   * @generated
   */
  int FORMAL_RESULT = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORMAL_RESULT__NAME = 0;

  /**
   * The feature id for the '<em><b>Timenodes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORMAL_RESULT__TIMENODES = 1;

  /**
   * The feature id for the '<em><b>Formal Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORMAL_RESULT__FORMAL_ELEMENTS = 2;

  /**
   * The number of structural features of the '<em>Formal Result</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORMAL_RESULT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.dsl.trace.impl.TimeNodeImpl <em>Time Node</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.dsl.trace.impl.TimeNodeImpl
   * @see org.xtext.example.dsl.trace.impl.TracePackageImpl#getTimeNode()
   * @generated
   */
  int TIME_NODE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME_NODE__NAME = 0;

  /**
   * The feature id for the '<em><b>Formalelement</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME_NODE__FORMALELEMENT = 1;

  /**
   * The number of structural features of the '<em>Time Node</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME_NODE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.dsl.trace.impl.FormalElementImpl <em>Formal Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.dsl.trace.impl.FormalElementImpl
   * @see org.xtext.example.dsl.trace.impl.TracePackageImpl#getFormalElement()
   * @generated
   */
  int FORMAL_ELEMENT = 2;

  /**
   * The feature id for the '<em><b>Formal Element</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORMAL_ELEMENT__FORMAL_ELEMENT = 0;

  /**
   * The feature id for the '<em><b>Element</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORMAL_ELEMENT__ELEMENT = 1;

  /**
   * The number of structural features of the '<em>Formal Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORMAL_ELEMENT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.dsl.trace.impl.ElementImpl <em>Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.dsl.trace.impl.ElementImpl
   * @see org.xtext.example.dsl.trace.impl.TracePackageImpl#getElement()
   * @generated
   */
  int ELEMENT = 3;

  /**
   * The feature id for the '<em><b>Type Element</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__TYPE_ELEMENT = 0;

  /**
   * The feature id for the '<em><b>Uml Element</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__UML_ELEMENT = 1;

  /**
   * The feature id for the '<em><b>Diagram</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__DIAGRAM = 2;

  /**
   * The feature id for the '<em><b>Model</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__MODEL = 3;

  /**
   * The number of structural features of the '<em>Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.dsl.trace.impl.DiagramImpl <em>Diagram</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.dsl.trace.impl.DiagramImpl
   * @see org.xtext.example.dsl.trace.impl.TracePackageImpl#getDiagram()
   * @generated
   */
  int DIAGRAM = 4;

  /**
   * The feature id for the '<em><b>Kind</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIAGRAM__KIND = 0;

  /**
   * The feature id for the '<em><b>Model</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIAGRAM__MODEL = 1;

  /**
   * The number of structural features of the '<em>Diagram</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIAGRAM_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.dsl.trace.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.dsl.trace.impl.ModelImpl
   * @see org.xtext.example.dsl.trace.impl.TracePackageImpl#getModel()
   * @generated
   */
  int MODEL = 5;

  /**
   * The feature id for the '<em><b>Kind</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__KIND = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.dsl.trace.DiagramKind <em>Diagram Kind</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.dsl.trace.DiagramKind
   * @see org.xtext.example.dsl.trace.impl.TracePackageImpl#getDiagramKind()
   * @generated
   */
  int DIAGRAM_KIND = 6;

  /**
   * The meta object id for the '{@link org.xtext.example.dsl.trace.ModelKind <em>Model Kind</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.dsl.trace.ModelKind
   * @see org.xtext.example.dsl.trace.impl.TracePackageImpl#getModelKind()
   * @generated
   */
  int MODEL_KIND = 7;


  /**
   * Returns the meta object for class '{@link org.xtext.example.dsl.trace.FormalResult <em>Formal Result</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Formal Result</em>'.
   * @see org.xtext.example.dsl.trace.FormalResult
   * @generated
   */
  EClass getFormalResult();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.dsl.trace.FormalResult#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.dsl.trace.FormalResult#getName()
   * @see #getFormalResult()
   * @generated
   */
  EAttribute getFormalResult_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.dsl.trace.FormalResult#getTimenodes <em>Timenodes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Timenodes</em>'.
   * @see org.xtext.example.dsl.trace.FormalResult#getTimenodes()
   * @see #getFormalResult()
   * @generated
   */
  EReference getFormalResult_Timenodes();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.dsl.trace.FormalResult#getFormalElements <em>Formal Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Formal Elements</em>'.
   * @see org.xtext.example.dsl.trace.FormalResult#getFormalElements()
   * @see #getFormalResult()
   * @generated
   */
  EReference getFormalResult_FormalElements();

  /**
   * Returns the meta object for class '{@link org.xtext.example.dsl.trace.TimeNode <em>Time Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Time Node</em>'.
   * @see org.xtext.example.dsl.trace.TimeNode
   * @generated
   */
  EClass getTimeNode();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.dsl.trace.TimeNode#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.dsl.trace.TimeNode#getName()
   * @see #getTimeNode()
   * @generated
   */
  EAttribute getTimeNode_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.dsl.trace.TimeNode#getFormalelement <em>Formalelement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Formalelement</em>'.
   * @see org.xtext.example.dsl.trace.TimeNode#getFormalelement()
   * @see #getTimeNode()
   * @generated
   */
  EReference getTimeNode_Formalelement();

  /**
   * Returns the meta object for class '{@link org.xtext.example.dsl.trace.FormalElement <em>Formal Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Formal Element</em>'.
   * @see org.xtext.example.dsl.trace.FormalElement
   * @generated
   */
  EClass getFormalElement();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.dsl.trace.FormalElement#getFormalElement <em>Formal Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Formal Element</em>'.
   * @see org.xtext.example.dsl.trace.FormalElement#getFormalElement()
   * @see #getFormalElement()
   * @generated
   */
  EReference getFormalElement_FormalElement();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.dsl.trace.FormalElement#getElement <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Element</em>'.
   * @see org.xtext.example.dsl.trace.FormalElement#getElement()
   * @see #getFormalElement()
   * @generated
   */
  EReference getFormalElement_Element();

  /**
   * Returns the meta object for class '{@link org.xtext.example.dsl.trace.Element <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Element</em>'.
   * @see org.xtext.example.dsl.trace.Element
   * @generated
   */
  EClass getElement();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.dsl.trace.Element#getTypeElement <em>Type Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Type Element</em>'.
   * @see org.xtext.example.dsl.trace.Element#getTypeElement()
   * @see #getElement()
   * @generated
   */
  EReference getElement_TypeElement();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.dsl.trace.Element#getUmlElement <em>Uml Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Uml Element</em>'.
   * @see org.xtext.example.dsl.trace.Element#getUmlElement()
   * @see #getElement()
   * @generated
   */
  EReference getElement_UmlElement();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.dsl.trace.Element#getDiagram <em>Diagram</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Diagram</em>'.
   * @see org.xtext.example.dsl.trace.Element#getDiagram()
   * @see #getElement()
   * @generated
   */
  EReference getElement_Diagram();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.dsl.trace.Element#getModel <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Model</em>'.
   * @see org.xtext.example.dsl.trace.Element#getModel()
   * @see #getElement()
   * @generated
   */
  EReference getElement_Model();

  /**
   * Returns the meta object for class '{@link org.xtext.example.dsl.trace.Diagram <em>Diagram</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Diagram</em>'.
   * @see org.xtext.example.dsl.trace.Diagram
   * @generated
   */
  EClass getDiagram();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.dsl.trace.Diagram#getKind <em>Kind</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Kind</em>'.
   * @see org.xtext.example.dsl.trace.Diagram#getKind()
   * @see #getDiagram()
   * @generated
   */
  EAttribute getDiagram_Kind();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.dsl.trace.Diagram#getModel <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Model</em>'.
   * @see org.xtext.example.dsl.trace.Diagram#getModel()
   * @see #getDiagram()
   * @generated
   */
  EReference getDiagram_Model();

  /**
   * Returns the meta object for class '{@link org.xtext.example.dsl.trace.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.dsl.trace.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.dsl.trace.Model#getKind <em>Kind</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Kind</em>'.
   * @see org.xtext.example.dsl.trace.Model#getKind()
   * @see #getModel()
   * @generated
   */
  EAttribute getModel_Kind();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.dsl.trace.DiagramKind <em>Diagram Kind</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Diagram Kind</em>'.
   * @see org.xtext.example.dsl.trace.DiagramKind
   * @generated
   */
  EEnum getDiagramKind();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.dsl.trace.ModelKind <em>Model Kind</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Model Kind</em>'.
   * @see org.xtext.example.dsl.trace.ModelKind
   * @generated
   */
  EEnum getModelKind();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  TraceFactory getTraceFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.dsl.trace.impl.FormalResultImpl <em>Formal Result</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.dsl.trace.impl.FormalResultImpl
     * @see org.xtext.example.dsl.trace.impl.TracePackageImpl#getFormalResult()
     * @generated
     */
    EClass FORMAL_RESULT = eINSTANCE.getFormalResult();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FORMAL_RESULT__NAME = eINSTANCE.getFormalResult_Name();

    /**
     * The meta object literal for the '<em><b>Timenodes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FORMAL_RESULT__TIMENODES = eINSTANCE.getFormalResult_Timenodes();

    /**
     * The meta object literal for the '<em><b>Formal Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FORMAL_RESULT__FORMAL_ELEMENTS = eINSTANCE.getFormalResult_FormalElements();

    /**
     * The meta object literal for the '{@link org.xtext.example.dsl.trace.impl.TimeNodeImpl <em>Time Node</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.dsl.trace.impl.TimeNodeImpl
     * @see org.xtext.example.dsl.trace.impl.TracePackageImpl#getTimeNode()
     * @generated
     */
    EClass TIME_NODE = eINSTANCE.getTimeNode();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TIME_NODE__NAME = eINSTANCE.getTimeNode_Name();

    /**
     * The meta object literal for the '<em><b>Formalelement</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TIME_NODE__FORMALELEMENT = eINSTANCE.getTimeNode_Formalelement();

    /**
     * The meta object literal for the '{@link org.xtext.example.dsl.trace.impl.FormalElementImpl <em>Formal Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.dsl.trace.impl.FormalElementImpl
     * @see org.xtext.example.dsl.trace.impl.TracePackageImpl#getFormalElement()
     * @generated
     */
    EClass FORMAL_ELEMENT = eINSTANCE.getFormalElement();

    /**
     * The meta object literal for the '<em><b>Formal Element</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FORMAL_ELEMENT__FORMAL_ELEMENT = eINSTANCE.getFormalElement_FormalElement();

    /**
     * The meta object literal for the '<em><b>Element</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FORMAL_ELEMENT__ELEMENT = eINSTANCE.getFormalElement_Element();

    /**
     * The meta object literal for the '{@link org.xtext.example.dsl.trace.impl.ElementImpl <em>Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.dsl.trace.impl.ElementImpl
     * @see org.xtext.example.dsl.trace.impl.TracePackageImpl#getElement()
     * @generated
     */
    EClass ELEMENT = eINSTANCE.getElement();

    /**
     * The meta object literal for the '<em><b>Type Element</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ELEMENT__TYPE_ELEMENT = eINSTANCE.getElement_TypeElement();

    /**
     * The meta object literal for the '<em><b>Uml Element</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ELEMENT__UML_ELEMENT = eINSTANCE.getElement_UmlElement();

    /**
     * The meta object literal for the '<em><b>Diagram</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ELEMENT__DIAGRAM = eINSTANCE.getElement_Diagram();

    /**
     * The meta object literal for the '<em><b>Model</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ELEMENT__MODEL = eINSTANCE.getElement_Model();

    /**
     * The meta object literal for the '{@link org.xtext.example.dsl.trace.impl.DiagramImpl <em>Diagram</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.dsl.trace.impl.DiagramImpl
     * @see org.xtext.example.dsl.trace.impl.TracePackageImpl#getDiagram()
     * @generated
     */
    EClass DIAGRAM = eINSTANCE.getDiagram();

    /**
     * The meta object literal for the '<em><b>Kind</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DIAGRAM__KIND = eINSTANCE.getDiagram_Kind();

    /**
     * The meta object literal for the '<em><b>Model</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIAGRAM__MODEL = eINSTANCE.getDiagram_Model();

    /**
     * The meta object literal for the '{@link org.xtext.example.dsl.trace.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.dsl.trace.impl.ModelImpl
     * @see org.xtext.example.dsl.trace.impl.TracePackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Kind</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODEL__KIND = eINSTANCE.getModel_Kind();

    /**
     * The meta object literal for the '{@link org.xtext.example.dsl.trace.DiagramKind <em>Diagram Kind</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.dsl.trace.DiagramKind
     * @see org.xtext.example.dsl.trace.impl.TracePackageImpl#getDiagramKind()
     * @generated
     */
    EEnum DIAGRAM_KIND = eINSTANCE.getDiagramKind();

    /**
     * The meta object literal for the '{@link org.xtext.example.dsl.trace.ModelKind <em>Model Kind</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.dsl.trace.ModelKind
     * @see org.xtext.example.dsl.trace.impl.TracePackageImpl#getModelKind()
     * @generated
     */
    EEnum MODEL_KIND = eINSTANCE.getModelKind();

  }

} //TracePackage
