/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mapping.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.example.mapping.ui.AbstractMappingUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class MappingUiModule extends AbstractMappingUiModule {
  public MappingUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
