/*
 * generated by Xtext 2.9.1
 */
package org.xtext.example.dsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class TraceStandaloneSetup extends TraceStandaloneSetupGenerated {

	def static void doSetup() {
		new TraceStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
