/*
 * generated by Xtext 2.9.1
 */
package org.xtext.example.dsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class TraceRuntimeModule extends AbstractTraceRuntimeModule {
}
