/*
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mapping.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMappingScopeProvider extends DelegatingScopeProvider {
}
