/*
 * generated by Xtext 2.9.1
 */
package org.xtext.example.dsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.dsl.parser.antlr.internal.InternalTraceParser;
import org.xtext.example.dsl.services.TraceGrammarAccess;

public class TraceParser extends AbstractAntlrParser {

	@Inject
	private TraceGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalTraceParser createParser(XtextTokenStream stream) {
		return new InternalTraceParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "FormalResult";
	}

	public TraceGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TraceGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
